### PR TITLE
Update messages.json

### PR DESCRIPTION
**Pull request by meinereina**
i have change some translations to native german ... because for an german it sounds terrible ;)

---

This change is [Reviewable](https://reviewable.io/reviews/pd75/practical-startpage/103)

### CODE REVIEW

**Comment by PD75** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pd75/practical-startpage/103)_

**Comment by PD75** [comment]
@meinereina 

Thank you for the help!

I have more that needs translation. 
Options:
1. I send a Google translate link with new words
2. You branch my code from (sync-storage) and check the English master version and add missing parts to German.

Which do you prefer?

**Comment by meinereina** [comment]
please send me the google translate link 

cheers Robert

**Comment by PD75** [comment]
@meinereina 

I need a google account to send it to, create a new topic here: https://groups.google.com/forum/#!forum/practical-startpage

Say that you want to translate German then I can send you the translate link.

I use this forum since only I can see your account there.

Best Regards

Paul

**Pull request merged**
